const $=id=>document.getElementById(id);
function etParts(d){return new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',weekday:'short',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).formatToParts(d).reduce((o,p)=>(o[p.type]=p.value,o),{})}
function etDate(y,m,d,h,min=0,s=0){const g=new Date(Date.UTC(y,m-1,d,h,min,s)),p=etParts(g),shown=Date.UTC(+p.year,+p.month-1,+p.day,+p.hour,+p.minute,+p.second),wanted=Date.UTC(y,m-1,d,h,min,s);return new Date(g.getTime()+wanted-shown)}
function nextOpen(p){let c=etDate(+p.year,+p.month,+p.day,9,30);if(c<=new Date())c=new Date(c.getTime()+86400000);while(['Sat','Sun'].includes(etParts(c).weekday))c=new Date(c.getTime()+86400000);return c}
function fmt(ms){const t=Math.max(0,Math.floor(ms/1000)),h=Math.floor(t/3600),m=Math.floor((t%3600)/60),s=t%60;return[h,m,s].map(v=>String(v).padStart(2,'0')).join(':')}
function tick(){const now=new Date(),hour=now.getHours();$('greeting').textContent=`${hour<12?'Good morning':hour<18?'Good afternoon':'Good evening'}, Leo.`;$('liveDate').textContent=new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric'}).format(now);$('liveTime').textContent=new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit',second:'2-digit'}).format(now);const p=etParts(now),mins=(+p.hour)*60+(+p.minute),weekday=!['Sat','Sun'].includes(p.weekday);let target,status,label,sub,color='#efc65f';if(weekday&&mins>=570&&mins<960){target=etDate(+p.year,+p.month,+p.day,16);status='Market is open';label='REGULAR SESSION';sub='Closes at 4:00 PM ET';color='#62efa7'}else{target=nextOpen(p);status='Market is closed';label='NEXT OPEN';sub=`Opens ${etParts(target).weekday} at 9:30 AM ET`}$('marketStatus').textContent=status;$('marketLabel').textContent=label;$('marketSubtext').textContent=sub;$('marketCountdown').textContent=fmt(target-now);$('marketDot').style.background=color;$('marketDot').style.boxShadow=`0 0 14px ${color}`}
setInterval(tick,1000);tick();
const panel=$('atlasPanel');$('atlasOrb').onclick=()=>panel.classList.add('open');$('closePanel').onclick=()=>panel.classList.remove('open');
document.querySelectorAll('.quick button').forEach(b=>b.onclick=()=>{const a={brief:'Technology is leading, NVDA has the strongest relative volume, and today’s main risk is scheduled economic news. Your focus is to wait for confirmation.',watch:'NVDA ranks first for relative volume, QQQ confirms broader technology strength, and AAPL is near a continuation level. These are watch items—not automatic trades.',plan:'Mark levels, define maximum risk, and let the first 15 minutes establish direction.'};$('response').innerHTML=`<div class="message">${a[b.dataset.answer]}</div>`});
$('chatForm').onsubmit=e=>{e.preventDefault();const q=$('chatInput').value.trim();if(!q)return;$('response').innerHTML=`<div class="message">This prototype uses sample data, but Atlas would answer “${q}” using your live watchlist, market context, and journal history.</div>`;$('chatInput').value=''};
let timer,index=0,paused=false;const lines=[...document.querySelectorAll('#script p')];function openBrief(){clearInterval(timer);index=0;paused=false;lines.forEach(x=>x.classList.remove('active'));$('progress').style.width='0%';$('pause').textContent='Pause';$('briefModal').classList.add('open');timer=setInterval(()=>{if(paused)return;lines.forEach(x=>x.classList.remove('active'));if(index<lines.length){lines[index].classList.add('active');index++;$('progress').style.width=`${index/lines.length*100}%`}else clearInterval(timer)},1200)}function closeBrief(){clearInterval(timer);$('briefModal').classList.remove('open')}$('startBrief').onclick=openBrief;$('closeBrief').onclick=closeBrief;$('done').onclick=closeBrief;$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'Resume':'Pause'};
let dur=1;$('duration').onclick=()=>{dur=dur===1?3:dur===3?.5:1;$('duration').textContent=dur===.5?'30 sec':`${dur} min`;toast(`Briefing length set to ${dur===.5?'30 seconds':dur+' minute'+(dur>1?'s':'')}.`)};$('watchlistBtn').onclick=()=>toast('The full watchlist is ready for the next build step.');$('whyBtn').onclick=()=>{panel.classList.add('open');$('response').innerHTML='<div class="message">The outlook is moderately bullish because technology is leading and futures are positive. Confidence is limited because volume is light and important events remain scheduled.</div>'};function toast(m){$('toast').textContent=m;$('toast').classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>$('toast').classList.remove('show'),2400)}
